### ISSUE TITLE
Compiling on Centos 6.4

### ISSUE THREAD

**Issue by Keithsc** [plashchynski/viewssld#5]
Hi. Am having trouble getting viewssld to build on Centos 6.4 x64. Any help would be appreciated. 

[root@Svr123 src]# make
gcc -DPACKAGE_NAME=\"viewssld\" -DPACKAGE_TARNAME=\"viewssld\" -DPACKAGE_VERSION=\"0.6.0\" -DPACKAGE_STRING=\"viewssld\ 0.6.0\" -DPACKAGE_BUGREPORT=\"plashchynski@gmail.com\" -DPACKAGE=\"viewssld\" -DVERSION=\"0.6.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_WAIT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_ARPA_INET_H=1 -DHAVE_NETINET_IN_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_SYS_IOCTL_H=1 -DHAVE_SYS_SOCKET_H=1 -DHAVE_SYSLOG_H=1 -DHAVE_UNISTD_H=1 -I.     -g -O2 -MT viewssld.o -MD -MP -MF .deps/viewssld.Tpo -c -o viewssld.o viewssld.c
In file included from viewssld.c:40:
utils.h:27: error: conflicting types for âSessionToStringâ
/usr/local/include/dssl/session.h:68: note: previous declaration of âSessionToStringâ was here
viewssld.c: In function âproceedâ:
viewssld.c:320: error: too few arguments to function âCapEnvCreateâ
viewssld.c: In function âsession_event_handlerâ:
viewssld.c:374: warning: passing argument 2 of âSessionSetCallbackâ from incompatible pointer type
/usr/local/include/dssl/session.h:83: note: expected âDataCallbackProcâ but argument is of type âvoid (_)(enum NM_PacketDir,  void *, u_char *, uint32_t)â
make: *_\* [viewssld.o] Error 1
[root@Svr123 src]#

Thanks
keith
